//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package perfectNumbersApp;

/** @hidden */
public class _ClientNotifierPrxI extends com.zeroc.Ice._ObjectPrxI implements ClientNotifierPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
