//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.perfectNumbers;

/** @hidden */
public class _WorkerServicePrxI extends com.zeroc.Ice._ObjectPrxI implements WorkerServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
