//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.perfectNumbers;

public interface ClientNotifierPrx extends com.zeroc.Ice.ObjectPrx
{
    default void notifyJobCompletion(Range originalRange, long[] perfectNumbers, String statusMessage, long elapsedTimeMillis)
    {
        notifyJobCompletion(originalRange, perfectNumbers, statusMessage, elapsedTimeMillis, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyJobCompletion(Range originalRange, long[] perfectNumbers, String statusMessage, long elapsedTimeMillis, java.util.Map<String, String> context)
    {
        _iceI_notifyJobCompletionAsync(originalRange, perfectNumbers, statusMessage, elapsedTimeMillis, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyJobCompletionAsync(Range originalRange, long[] perfectNumbers, String statusMessage, long elapsedTimeMillis)
    {
        return _iceI_notifyJobCompletionAsync(originalRange, perfectNumbers, statusMessage, elapsedTimeMillis, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyJobCompletionAsync(Range originalRange, long[] perfectNumbers, String statusMessage, long elapsedTimeMillis, java.util.Map<String, String> context)
    {
        return _iceI_notifyJobCompletionAsync(originalRange, perfectNumbers, statusMessage, elapsedTimeMillis, context, false);
    }

    /**
     * @hidden
     * @param iceP_originalRange -
     * @param iceP_perfectNumbers -
     * @param iceP_statusMessage -
     * @param iceP_elapsedTimeMillis -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyJobCompletionAsync(Range iceP_originalRange, long[] iceP_perfectNumbers, String iceP_statusMessage, long iceP_elapsedTimeMillis, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyJobCompletion", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Range.ice_write(ostr, iceP_originalRange);
                     ostr.writeLongSeq(iceP_perfectNumbers);
                     ostr.writeString(iceP_statusMessage);
                     ostr.writeLong(iceP_elapsedTimeMillis);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ClientNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ClientNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ClientNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ClientNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ClientNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ClientNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ClientNotifierPrx.class, _ClientNotifierPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ClientNotifierPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ClientNotifierPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ClientNotifierPrx ice_adapterId(String newAdapterId)
    {
        return (ClientNotifierPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ClientNotifierPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ClientNotifierPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ClientNotifierPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ClientNotifierPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ClientNotifierPrx ice_invocationTimeout(int newTimeout)
    {
        return (ClientNotifierPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ClientNotifierPrx ice_connectionCached(boolean newCache)
    {
        return (ClientNotifierPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ClientNotifierPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ClientNotifierPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ClientNotifierPrx ice_secure(boolean b)
    {
        return (ClientNotifierPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ClientNotifierPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ClientNotifierPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ClientNotifierPrx ice_preferSecure(boolean b)
    {
        return (ClientNotifierPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ClientNotifierPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ClientNotifierPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ClientNotifierPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ClientNotifierPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ClientNotifierPrx ice_collocationOptimized(boolean b)
    {
        return (ClientNotifierPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ClientNotifierPrx ice_twoway()
    {
        return (ClientNotifierPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ClientNotifierPrx ice_oneway()
    {
        return (ClientNotifierPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ClientNotifierPrx ice_batchOneway()
    {
        return (ClientNotifierPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ClientNotifierPrx ice_datagram()
    {
        return (ClientNotifierPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ClientNotifierPrx ice_batchDatagram()
    {
        return (ClientNotifierPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ClientNotifierPrx ice_compress(boolean co)
    {
        return (ClientNotifierPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ClientNotifierPrx ice_timeout(int t)
    {
        return (ClientNotifierPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ClientNotifierPrx ice_connectionId(String connectionId)
    {
        return (ClientNotifierPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ClientNotifierPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ClientNotifierPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::PerfectNumbersApp::src::main::java::com::example::perfectNumbers::ClientNotifier";
    }
}
