//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.perfectNumbers;

public class Range implements java.lang.Cloneable,
                              java.io.Serializable
{
    public long start;

    public long end;

    public Range()
    {
    }

    public Range(long start, long end)
    {
        this.start = start;
        this.end = end;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Range r = null;
        if(rhs instanceof Range)
        {
            r = (Range)rhs;
        }

        if(r != null)
        {
            if(this.start != r.start)
            {
                return false;
            }
            if(this.end != r.end)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::PerfectNumbersApp::src::main::java::com::example::perfectNumbers::Range");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, start);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, end);
        return h_;
    }

    public Range clone()
    {
        Range c = null;
        try
        {
            c = (Range)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.start);
        ostr.writeLong(this.end);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.start = istr.readLong();
        this.end = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Range v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Range ice_read(com.zeroc.Ice.InputStream istr)
    {
        Range v = new Range();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Range> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Range v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(16);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Range> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Range.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Range _nullMarshalValue = new Range();

    /** @hidden */
    public static final long serialVersionUID = -1134951290L;
}
